In [4]:
#import the numpy package under the name np
import numpy as np

In [5]:
#print the numpy version and the configuration
np.__version__
print("the version is ", np.__version__)
np.__config__.show() 

the version is  1.24.4
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/cipher/miniconda3/envs/mytest/lib']
    include_dirs = ['/home/cipher/miniconda3/envs/mytest/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/cipher/miniconda3/envs/mytest/lib']
    include_dirs = ['/home/cipher/miniconda3/envs/mytest/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/cipher/miniconda3/envs/mytest/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/cipher/miniconda3/envs/mytest/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/cipher/miniconda3/envs/

In [6]:
array = np.array([1, 2, 3, 4, 5])
print(type(array)) 

<class 'numpy.ndarray'>


In [7]:
#using a tuple to create a ndarray
array = np.array((1,2,3,4,5))  
print(array) 
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#create a null vector of size 10
null_vector= np.zeros(10)
print(null_vector)
print(len(null_vector))



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


In [9]:
null_vector= np.zeros(10)
print(null_vector) 
null_vector[5]=1
print(null_vector)
print(len(null_vector))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
10


#### How to get the documentation of the numpy add function from the command line ?

In [11]:
python -c  "import numpy; numpy.info(numpy.add)"


SyntaxError: invalid syntax (2528908272.py, line 1)

 #### Create a null vector of size 10 but the fifth value which is 1

In [12]:
Z= np.zeros(10)
Z[4]= 1
print (Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49

In [13]:
Z=np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a vector (first element becomes last)

In [14]:
Z = np.arange(10,50)
Z= Z[::-1]
print (Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 ### Find indices of non-zero elements from [1,2,0,0,4,0]

In [16]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


### Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### Create a 3x3 identity matrix

In [18]:
Z= np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Create a 3x3x3 array with random values

In [19]:
Z = np.random.uniform((3,3,3))
print (Z)

[1.86253617 1.19230887 1.70767338]


### Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01124016212403156 0.9894856603104696


### Create a random vector of size 30 and find the mean value

In [26]:
Z = np.random.random(10)
m = Z.mean()
print (m)

0.3383994335038481


### Create a 2d array with 1 on the border and 0 inside

In [21]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0


#### What is the result of the following expression ?

In [22]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [23]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Create a 8x8 matrix and fill it with a checkerboard pattern

In [24]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Create a 8x8 matrix and fill it with a checkerboard pattern

### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element ?

In [25]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


### Create a checkerboard 8x8 matrix using the tile function

In [26]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Normalize a 5x5 random matrix

In [27]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.83021739 0.71169981 0.1234531  0.70351919 0.84587732]
 [0.27108912 0.         0.60283764 0.61013596 0.6821954 ]
 [0.56969859 0.27911015 0.77450074 0.34583715 0.88420436]
 [0.79903442 0.92508438 0.65388825 0.07335608 0.76735536]
 [0.4945965  0.89629502 0.5902777  1.         0.8054638 ]]


### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [28]:
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)



In [29]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### What is the output of the following script?

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


### Consider an integer vector Z, which of these expressions are legal?

In [31]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

### What are the result of the following expressions? 

In [32]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_1955/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_1955/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_1955/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? 

In [33]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[  1.   1. -10. -10.  10.  -3.  10. -10.  -7. -10.]


#### 30. How to find common values between two arrays? (★☆☆)


In [34]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[0 1 2 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [36]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


In [37]:
# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


### Is the following expressions true? 

In [38]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_1955/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [39]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_1955/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [41]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [42]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [43]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [44]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[3. 4. 3. 7. 4. 3. 5. 7. 1. 1.]
[3. 4. 3. 7. 4. 3. 5. 7. 1. 1.]
[3. 4. 3. 7. 4. 3. 5. 7. 1. 1.]
[3 4 3 7 4 3 5 7 1 1]
[3. 4. 3. 7. 4. 3. 5. 7. 1. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [45]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [46]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [47]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)


In [48]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.07921227 0.27323467 0.37258889 0.58782418 0.7486737  0.81353765
 0.86961484 0.95673649 0.97045201 0.97950543]


#### 41. How to sum a small array faster than np.sum? (★★☆)


In [49]:
Z = np.arange(10)
np.add.reduce(Z)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [50]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)


In [51]:
equal = np.allclose(A,B)
print(equal)


False


In [52]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


False


#### 43. Make an array immutable (read-only) (★★☆)


In [53]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [54]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.51171745 1.20079377 1.03369555 0.83048656 0.38814886 1.11472304
 0.60366658 0.57864562 1.21216725 0.91582583]
[1.05499199 0.91113417 0.89938121 1.33770406 0.83868175 0.6772199
 0.41172758 0.70586321 0.70911068 1.21881315]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [55]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.58141152 0.11493556 0.22936839 0.6646674  0.41875789 0.6649858
 0.80794768 0.         0.24146843 0.10640367]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [58]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [59]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [61]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)


In [63]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((10,10))
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
